version: '3.8'

services:

  imagelab-ui:
    container_name: imagelab-ui
    image: imagelab/imagelab-ui:v0.0.1
    restart: always
    ports:
      - '127.0.0.1:90:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - imagelab-network

  nginx:
    container_name: nginx
    image: imagelab/nginx:v0.0.1
    restart: always
    ports:
      - "127.0.0.1:8082:8080"
    networks:
      - imagelab-network

  imagelab-python-fastapi:
    container_name: imagelab-python-fastapi
    image: imagelab/imagelab-python-fastapi:v0.0.1
    restart: always
    ports:
      - "127.0.0.1:8083:8083"
    networks:
      - imagelab-network

networks:
  decido-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
